package models

case class Header(id: String,
                  parentId: String,
                  version: Short,
                  height: Int,
                  adProofsRoot: String,
                  stateRoot: String,
                  transactionsRoot: String,
                  timestamp: Long,
                  nonce: Long,
                  difficulty: Long,
                  blockSize: Long,
                  equihashSolutions: String,
                  adProofsOpt: Option[String],
                  txsQty: Long,
                  minerAddress: String,
                  minerReward: Long,
                  feesTotal: Long,
                  txsSize: Long,
                  bestChain: Boolean)